/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.addere.mdg.app

import ch.addere.mdg.app.domain.model.CommandArgument
import ch.addere.mdg.app.domain.service.DependencyCommand
import ch.addere.mdg.app.infrastructure.factory.dgaModule
import ch.addere.mdg.app.infrastructure.factory.userInputModule
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.help
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.help
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.file
import org.koin.core.component.KoinComponent
import org.koin.core.component.get
import org.koin.core.context.GlobalContext.startKoin
import org.koin.core.parameter.parametersOf
import java.io.File
import kotlin.system.exitProcess

class Dga : CliktCommand(help = "Analyse the dependency graph of a Gradle project."),
    KoinComponent {

    private val settingsFile: File by argument()
        .file()
        .help("Gradle settings file or parent folder containing one")

    private val isMermaidGraph: Boolean by option("--mermaid-graph")
        .flag()
        .help("Generate Mermaid graph useful to visualise a graph chart")

    private val isAllModules: Boolean by option("--modules")
        .flag()
        .help("Shows all modules ordered alphabetically")

    private val isAllConfigurations: Boolean by option("--configurations")
        .flag()
        .help("Shows all configurations ordered by occurrence")

    override fun run() {
        val argument =
            CommandArgument(::echo, settingsFile, isMermaidGraph, isAllModules, isAllConfigurations)
        val command: DependencyCommand = get { parametersOf(argument) }

        command.run()
    }
}

fun main(args: Array<String>) {
    val dga = Dga()
    try {
        startKoin {
            modules(userInputModule)
            modules(dgaModule)
        }

        dga.parse(args)
    } catch (e: CliktError) {
        dga.echoFormattedHelp(e)
        exitProcess(e.statusCode)
    } catch (e: Exception) {
        dga.echo(e.message, err = true)
        exitProcess(1)
    }
}
